// class Post{
//     constructor (titlePost, topicID, dateUpload, summary, contentID, permission){
//         this.titlePost = titlePost;
//         this.topicID = topicID;
//         this.dateUpload = dateUpload;
//         this.summary = summary;
//         this.contentID = contentID;
//         this.permission = permission;
//     }
// }
// module.exports = Post;

const list= [
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi sang', topicID: 1, dateUpload:'1/1/2000',summary:'bai bao viet cho vui',contentID:112,permission:1},
    {id:1123, titlePost: 'Chao buoi chieu', topicID: 2, dateUpload:'2/1/2000',summary:'bai bao viet cho vui',contentID:113,permission:1},
    {id:1123, titlePost: 'Chao buoi toi', topicID: 3, dateUpload:'3/1/2000',summary:'bai bao viet cho vui',contentID:123,permission:1},
    {id:1123, titlePost: 'Chao nua dem', topicID: 3, dateUpload:'4/1/2000',summary:'bai bao viet cho vui',contentID:113,permission:1},
    {id:1123, titlePost: 'Chao binh minh', topicID: 1, dateUpload:'5/1/2000',summary:'bai bao viet cho vui',contentID:1123,permission:2}
];
const users =[
    {   id: 1,
        userName: 'nguyen minh nhat',
        password: '123asdqwe',
        profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
        permission: 1,
        gmail: 'abc@gmail.com',
        phoneNumber: 123456789,
        dayOfBirth: '1/1/1223',
        dayInit: '21/3/2000',
        dayInitPremeum: '21/1/2021',
        dayEndPremeum: '21/3/2021',
        nameOfUser: 'bknight',
        nickName: 'xxy'},{   id: 1,
            userName: 'nguyen minh nhat',
            password: '123asdqwe',
            profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
            permission: 1,
            gmail: 'abc@gmail.com',
            phoneNumber: 123456789,
            dayOfBirth: '1/1/1223',
            dayInit: '21/3/2000',
            dayInitPremeum: '21/1/2021',
            dayEndPremeum: '21/3/2021',
            nameOfUser: 'bknight',
            nickName: 'xxy'},{   id: 1,
                userName: 'nguyen minh nhat',
                password: '123asdqwe',
                profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                permission: 1,
                gmail: 'abc@gmail.com',
                phoneNumber: 123456789,
                dayOfBirth: '1/1/1223',
                dayInit: '21/3/2000',
                dayInitPremeum: '21/1/2021',
                dayEndPremeum: '21/3/2021',
                nameOfUser: 'bknight',
                nickName: 'xxy'},{   id: 1,
                    userName: 'nguyen minh nhat',
                    password: '123asdqwe',
                    profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                    permission: 1,
                    gmail: 'abc@gmail.com',
                    phoneNumber: 123456789,
                    dayOfBirth: '1/1/1223',
                    dayInit: '21/3/2000',
                    dayInitPremeum: '21/1/2021',
                    dayEndPremeum: '21/3/2021',
                    nameOfUser: 'bknight',
                    nickName: 'xxy'},{   id: 1,
                        userName: 'nguyen minh nhat',
                        password: '123asdqwe',
                        profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                        permission: 1,
                        gmail: 'abc@gmail.com',
                        phoneNumber: 123456789,
                        dayOfBirth: '1/1/1223',
                        dayInit: '21/3/2000',
                        dayInitPremeum: '21/1/2021',
                        dayEndPremeum: '21/3/2021',
                        nameOfUser: 'bknight',
                        nickName: 'xxy'},{   id: 1,
                            userName: 'nguyen minh nhat',
                            password: '123asdqwe',
                            profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                            permission: 1,
                            gmail: 'abc@gmail.com',
                            phoneNumber: 123456789,
                            dayOfBirth: '1/1/1223',
                            dayInit: '21/3/2000',
                            dayInitPremeum: '21/1/2021',
                            dayEndPremeum: '21/3/2021',
                            nameOfUser: 'bknight',
                            nickName: 'xxy'},{   id: 1,
                                userName: 'nguyen minh nhat',
                                password: '123asdqwe',
                                profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                permission: 1,
                                gmail: 'abc@gmail.com',
                                phoneNumber: 123456789,
                                dayOfBirth: '1/1/1223',
                                dayInit: '21/3/2000',
                                dayInitPremeum: '21/1/2021',
                                dayEndPremeum: '21/3/2021',
                                nameOfUser: 'bknight',
                                nickName: 'xxy'},{   id: 1,
                                    userName: 'nguyen minh nhat',
                                    password: '123asdqwe',
                                    profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                    permission: 1,
                                    gmail: 'abc@gmail.com',
                                    phoneNumber: 123456789,
                                    dayOfBirth: '1/1/1223',
                                    dayInit: '21/3/2000',
                                    dayInitPremeum: '21/1/2021',
                                    dayEndPremeum: '21/3/2021',
                                    nameOfUser: 'bknight',
                                    nickName: 'xxy'},{   id: 1,
                                        userName: 'nguyen minh nhat',
                                        password: '123asdqwe',
                                        profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                        permission: 1,
                                        gmail: 'abc@gmail.com',
                                        phoneNumber: 123456789,
                                        dayOfBirth: '1/1/1223',
                                        dayInit: '21/3/2000',
                                        dayInitPremeum: '21/1/2021',
                                        dayEndPremeum: '21/3/2021',
                                        nameOfUser: 'bknight',
                                        nickName: 'xxy'},{   id: 1,
                                            userName: 'nguyen minh nhat',
                                            password: '123asdqwe',
                                            profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                            permission: 1,
                                            gmail: 'abc@gmail.com',
                                            phoneNumber: 123456789,
                                            dayOfBirth: '1/1/1223',
                                            dayInit: '21/3/2000',
                                            dayInitPremeum: '21/1/2021',
                                            dayEndPremeum: '21/3/2021',
                                            nameOfUser: 'bknight',
                                            nickName: 'xxy'},{   id: 1,
                                                userName: 'nguyen minh nhat',
                                                password: '123asdqwe',
                                                profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                                permission: 1,
                                                gmail: 'abc@gmail.com',
                                                phoneNumber: 123456789,
                                                dayOfBirth: '1/1/1223',
                                                dayInit: '21/3/2000',
                                                dayInitPremeum: '21/1/2021',
                                                dayEndPremeum: '21/3/2021',
                                                nameOfUser: 'bknight',
                                                nickName: 'xxy'},{   id: 1,
                                                    userName: 'nguyen minh nhat',
                                                    password: '123asdqwe',
                                                    profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                                    permission: 1,
                                                    gmail: 'abc@gmail.com',
                                                    phoneNumber: 123456789,
                                                    dayOfBirth: '1/1/1223',
                                                    dayInit: '21/3/2000',
                                                    dayInitPremeum: '21/1/2021',
                                                    dayEndPremeum: '21/3/2021',
                                                    nameOfUser: 'bknight',
                                                    nickName: 'xxy'},{   id: 1,
                                                        userName: 'nguyen minh nhat',
                                                        password: '123asdqwe',
                                                        profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
                                                        permission: 1,
                                                        gmail: 'abc@gmail.com',
                                                        phoneNumber: 123456789,
                                                        dayOfBirth: '1/1/1223',
                                                        dayInit: '21/3/2000',
                                                        dayInitPremeum: '21/1/2021',
                                                        dayEndPremeum: '21/3/2021',
                                                        nameOfUser: 'bknight',
                                                        nickName: 'xxy'},
    {   id: 1,
        userName: 'nguyen minh nhat',
        password: '123asdqwe',
        profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
        permission: 1,
        gmail: 'abc@gmail.com',
        phoneNumber: '012345678',
        dayOfBirth: '1/1/1223',
        dayInit: '21/3/2000',
        dayInitPremeum: '21/1/2021',
        dayEndPremeum: '21/3/2021',
        nameOfUser: 'bknight',
        nickName: 'xxy'},
    {   id: 1,
        userName: 'nguyen minh nhat',
        password: '123asdqwe',
        profilePicture: 'https/asdlkjf.asdlkjgsd/sdf',
        permission: 1,
        gmail: 'abc@gmail.com',
        phoneNumber: '0123689',
        dayOfBirth: '1/1/1223',
        dayInit: '21/3/2000',
        dayInitPremeum: '21/1/2021',
        dayEndPremeum: '21/3/2021',
        nameOfUser: 'bknight',
        nickName: 'xxy'}
]
module.exports = {
    all(){return list;},
    alluser(){return users;}
}